config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'service/stores', to: 'stores#allStores'
  get 'service/articles', to: 'articles#allArticles'
  get 'service/articles/stores/:store_id', to: 'articles#store'

  resources :stores
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :store, inverse_of: :articles
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :articles, inverse_of: :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html
  respond_to :xml, :json, only: [ :store, :allArticles ]


  def index

    @articles = Article.all
  end

  def show
    @articles = Article.find(params[:article_id])
  end

  def create
    # save new article of a store, post method

    @article = Article.create(name: params[:article][:name], description:params[:article][:description], price: params[:article][:price],
    total_in_shelf: params[:article][:total_in_shelf], total_in_vault: params[:article][:total_in_vault], store_id: params[:article][:store])
    if @article.save
      # pass data to next action. Later you can show a message with this data
      # flash[:notice] = "Store successfully created"
      redirect_to(articles_path)
    else
      redirect_to(new_article_path)
    end
  end

  def new
    @stores = Store.all
  end

  def destroy
  end

  def store
    @store = Store.find(params[:store_id])
    @articles = @store.articles
    xml = Builder::XmlMarkup.new
    xml.instruct!
    xml.articles do
      @articles.each { |article|
        xml.id article.id
        xml.description article.description
        xml.name article.name
        xml.price article.price
        xml.total_in_shelf article.total_in_shelf
        xml.total_in_vault article.total_in_vault
        xml.store_name article.store.name
      }
    end
    xml.success(!@articles.empty?)
    xml.total_elements(@articles.count)
    respond_to do |format|
      format.json
      format.xml { render :xml => xml.target! }
    end
  end

  def allArticles
    @articles = Article.all
    xml = Builder::XmlMarkup.new
    xml.instruct!
    xml.articles do
      @articles.each { |article|
        xml.id article.id
        xml.description article.description
        xml.name article.name
        xml.price article.price
        xml.total_in_shelf article.total_in_shelf
        xml.total_in_vault article.total_in_vault
        xml.store_name article.store.name
      }
    end
    xml.success(!@articles.empty?)
    xml.total_elements(@articles.count)
    respond_to do |format|
      format.html { redirect_to(articles_path) }
      format.json
      format.xml { render :xml => xml.target! }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  respond_to :html
  respond_to :xml, :json, only: [ :allStores ]
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:store_id])
  end

  def create
    # save new store, post method

    @store = Store.create(name: params[:store][:name], address: params[:store][:address])
    if @store.save
      # pass data to next action. Later you can show a message with this data
      # flash[:notice] = "Store successfully created"
      redirect_to(stores_path)
    else
      redirect_to(new_store_path)
    end
  end

  def new
    # return html with form to create new store
  end


  def allStores
    @stores = Store.all
    xml = Builder::XmlMarkup.new
    xml.instruct!
    xml.stores do
      @stores.each { |store|
        xml.id store.id
        xml.address store.address
        xml.name store.name
      }
    end
    xml.success(!@stores.empty?)
    xml.total_elements(@stores.count)

    json.success !@stores.empty?
    json.total_elements @stores.count
    respond_to do |format|
      format.html { redirect_to(stores_path) }
      format.json
      format.xml {  render :xml => xml.target! }
    end
  end


  def destroy
    # Rails would dispatch that request to the destroy method on the photos controller with { id: '17' } in params.
    @store = Store.find(params[:store])
    @store.destroy
    redirect_to(stores_path)
  end

  def edit
    @store = Store.find(params[:store_id])
  end

  def update

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @appInfo = {title: 'Welcome! this is a Test of Rails App', subtitle:'choose your destiny...'}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/create.html.erb
<h1>Articles#create,</h1>
<p>Find me in app/views/articles/create,.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy,</h1>
<p>Find me in app/views/articles/destroy,.html.erb</p>

app/views/articles/index.html.erb
<h1>Listing all Articles: </h1>

<table>
  <tr>
    <th>name</th>
    <th>description</th>
    <th>price</th>
    <th>total in shelf</th>
    <th>total in vault</th>
    <th>store name</th>
  </tr>
  <% articles = Article.all %>
  <% articles.each do |article| %>
      <tr>
        <td><%=	article.name  %></td>
        <td><%=	article.description  %></td>
        <td><%=	article.price  %></td>
        <td><%=	article.total_in_shelf  %></td>
        <td><%=	article.total_in_vault  %></td>
        <td><%=	article.store.name  %></td>
        <td><%=	link_to "Edit", edit_article_path(article.id)  %></td>
        <td><%=	link_to "Delete", article, method: :delete  %></td>
      </tr>
  <% end %>
  <% if articles.size == 0 %>
      <em>No Articles Found</em>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create new Article</h1>
<p>add data to create new article:</p>


<%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.label :price %><br>
      <%= f.number_field :price %>
    </p>

    <p>
      <%= f.label :total_in_shelf %><br>
      <%= f.number_field :total_in_shelf %>
    </p>

    <p>
      <%= f.label :total_in_vault %><br>
      <%= f.number_field :total_in_vault %>
    </p>

    <p>
      <%= f.label :store %><br>
      <%= f.collection_select :store, Store.all, :id, :name,  include_blank: false  %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="innerContainer">
    <h1 id="title"> Admin <br> Shoe Stores</h1>
    <nav>
      <ul id="navigationContainer">
        <li><%=link_to "Add Store", new_store_path, class: "green"%></li>
        <li><%=link_to "Add Article", new_article_path, class: "green"%></li>
        <li><%=link_to "List all Articles", articles_path, class: "green"%></li>
        <li><%=link_to "List all Stores", stores_path, class: "green"%></li>
      </ul>
    </nav>
    <hr/>
  </div>
</header>
<section>
  <div class="innerContainer">
    <%= yield %>
  </div>
</section>

<footer>
  <div class="innerContainer">
      <hr/>
      <div class="footer-left">
        <h3>Company<span>logo</span></h3>
        <p class="footer-company-name">Company Name &copy; 2015</p>
      </div>

      <div class="footer-center">
          <p><span>21 Revolution Street</span> Paris, France</p><br/>
          <p>+1 555 123456</p><br/>
          <p><a href="mailto:support@company.com">support@company.com</a></p><br/>
      </div>

      <div class="footer-right">
        <p class="footer-company-about">
          <span>About the company</span>
          Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
        </p>
      </div>
  </div>
</footer>

</body>
</html>

app/views/stores/index.html.erb
<h1>Listing all Stores: </h1>

<table>
  <tr>
    <th>name</th>
    <th>address</th>
  </tr>
  <% stores = Store.all %>
  <% stores.each do |store| %>
  <tr>
    <td><%=	store.name  %></td>
    <td><%=	store.address  %></td>
    <td><%=	link_to "Edit", edit_store_path(store.id)  %></td>
    <td><%=	link_to "Delete", store, method: :delete  %></td>
  </tr>
  <% end %>
  <% if stores.size == 0 %>
    <em>No Stores Found</em>
  <% end %>
</table>

app/views/stores/new.html.erb
<h1>Create new store</h1>
<p>add data to create new store:</p>


<%= form_for :store, url: stores_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/stores/show.html.erb
<h1>Stores#stores</h1>
<p>Find me in app/views/stores/stores.html.erb</p>

app/views/stores/stores.html.erb
<h1>Stores#stores</h1>
<p>Find me in app/views/stores/stores.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome! this is a Test of a Rails App</h1>
<h3>choose your destiny... </h3>